src/TFLDataExplorer/Controllers/AirQualityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using TFLDataExplorer.Models;
using System.Collections;

namespace TFLDataExplorer.Controllers
{
    public class AirQualityController : Controller
    {
        private readonly MyOptions _optionsAccessor;
        private readonly IAPIContextAsync _apiContextAsync;

        public AirQualityController(IOptions<MyOptions> optionsAccessor, IAPIContextAsync apiContextAsync)
        {
            _optionsAccessor = optionsAccessor.Value;
            _apiContextAsync = apiContextAsync;
        }


        public async Task<ActionResult> Index()
        {
            // Get the current Air Quality status
            var model = await _apiContextAsync.GetObjectAsync<AirQualityModel>(string.Format("AirQuality/?app_id={1}{0}app_key={2}", "&", _optionsAccessor.AppId, _optionsAccessor.AppKey));
           

            return View(model);
        }


        public IActionResult Error()
        {

            return View();
        }
    }
}

src/TFLDataExplorer/Controllers/DLRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using TFLDataExplorer.Models;
using System.Collections;

namespace TFLDataExplorer.Controllers
{
    public class DLRController : Controller
    {
        private readonly MyOptions _optionsAccessor;
        private readonly IAPIContextAsync _apiContextAsync;

        public DLRController(IOptions<MyOptions> optionsAccessor, IAPIContextAsync apiContextAsync)
        {
            _optionsAccessor = optionsAccessor.Value;
            _apiContextAsync = apiContextAsync;
        }


        public async Task<ActionResult> Index()
        {
            // Declare which Mode we want to request Line data for.
            var mode = "dlr";

            // Get the current Line status for the given mode (dlr).
            var model = await _apiContextAsync.GetObjectsAsync<LineModel>(string.Format("Line/Mode/{0}/Status?detail=false{1}app_id={2}{1}app_key={3}", mode, "&", _optionsAccessor.AppId, _optionsAccessor.AppKey));


            return View(model);
        }



        public async Task<ActionResult> Detail(string name)
        {
            // Get the current Line status for the given line.
            var model = await _apiContextAsync.GetObjectsAsync<LineModel>(string.Format("Line/{0}?app_id={2}{1}app_key={3}", name, "&", _optionsAccessor.AppId, _optionsAccessor.AppKey));


            return View(model);
        }


        public IActionResult Error()
        {

            return View();
        }
    }
}

src/TFLDataExplorer/Controllers/StationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using TFLDataExplorer.Models;
using System.Collections;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TFLDataExplorer.Controllers
{
    public class StationController : Controller
    {
        private readonly MyOptions _optionsAccessor;
        private readonly IStationService _stationService;

        public StationController(IOptions<MyOptions> optionsAccessor, IStationService stationService)
        {
            _optionsAccessor = optionsAccessor.Value;
            _stationService = stationService;
        
        }

        public async Task<IActionResult> Index()
        {
            // Get the list of Stations and their facilities from the TFL Feed.
            var model = await _stationService.GetStationsAsync(string.Format("https://data.tfl.gov.uk/tfl/syndication/feeds/stations-facilities.xml?app_id={0}&app_key={1}", _optionsAccessor.AppId, _optionsAccessor.AppKey));
            

            return View(model);
        }

        // Action result for Ajax call.
        [HttpPost]
        public async Task<ActionResult> GetStationsByZone(string zoneid)
        {
            // Get the list of Stations and their facilities from the TFL Feed.
            var model = await _stationService.GetStationsAsync(string.Format("https://data.tfl.gov.uk/tfl/syndication/feeds/stations-facilities.xml?app_id={0}&app_key={1}", _optionsAccessor.AppId, _optionsAccessor.AppKey));

            // Get a List of Stations that are in the Zone selected by the user.
            var stationListbyZone = model.Stations.Station.Where(x => x.Zones.Zone == zoneid).ToList();

            SelectList stationSelectList = new SelectList(stationListbyZone, "Id", "Name", 0);


            return Json(stationSelectList);
        }


        [HttpPost]
        public async Task<ActionResult> GetStationById(string stationid)
        {
            // Get the list of Stations and their facilities from the TFL Feed.
            var model = await _stationService.GetStationsAsync(string.Format("https://data.tfl.gov.uk/tfl/syndication/feeds/stations-facilities.xml?app_id={0}&app_key={1}", _optionsAccessor.AppId, _optionsAccessor.AppKey));

            // Get the Station with the Id selected by the user.
            var station = model.Stations.Station.Where(x => x.Id == stationid);


            return PartialView("_Station", station);
        }


        public IActionResult Error()
        {

            return View();
        }
    }
}

src/TFLDataExplorer/Controllers/TubeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using TFLDataExplorer.Models;
using System.Collections;
using Newtonsoft.Json;
using Moq;

namespace TFLDataExplorer.Controllers
{
    public class TubeController : Controller
    {
        private readonly MyOptions _optionsAccessor;
        private readonly IAPIContextAsync _apiContextAsync;

        public TubeController(IOptions<MyOptions> optionsAccessor, IAPIContextAsync apiContextAsync)
        {
            _optionsAccessor = optionsAccessor.Value;
            _apiContextAsync = apiContextAsync;
        }

        public async Task<ActionResult> Index()
        {
            // Declare which Mode we want to request Line data for.
            var mode = "tube";

            // Get the current Line status for the given mode (tube).
            var model = await _apiContextAsync.GetObjectsAsync<LineModel>(string.Format("Line/Mode/{0}/Status?detail=false{1}app_id={2}{1}app_key={3}", mode, "&", _optionsAccessor.AppId, _optionsAccessor.AppKey));

            model = model.OrderByDescending(x => x.lineStatuses.Sum(s => s.statusSeverity)).ToList();


            return View(model);
        }


        public async Task<ActionResult> Detail(string name)
        {
            // Get the current Line status for the given line.
            var model = await _apiContextAsync.GetObjectsAsync<LineModel>(string.Format("Line/{0}?app_id={2}{1}app_key={3}", name, "&", _optionsAccessor.AppId, _optionsAccessor.AppKey));

            return View(model);
        }


        public async Task<ActionResult> Status(string name)
        {
            // Get the current Line status for the given line.
            var model = await _apiContextAsync.GetObjectsAsync<LineModel>(string.Format("Line/{0}/Status?app_id={2}{1}app_key={3}", name, "&", _optionsAccessor.AppId, _optionsAccessor.AppKey));


            return View(model);
        }


        public IActionResult Error()
        {

            return View();
        }
    }
}

src/TFLDataExplorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TFL Data Explorer</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <script src="~/lib/jquery/dist/jquery.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TFL Data Explorer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Tube" asp-action="Index">Tube</a></li>
                    <li><a asp-area="" asp-controller="DLR" asp-action="Index">DLR</a></li>
                    <li><a asp-area="" asp-controller="AirQuality" asp-action="Index">Air Quality</a></li>
                    <li><a asp-area="" asp-controller="Station" asp-action="Index">Stations</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <p></p>
        <div class="container body-content">
            @RenderBody() 
            @RenderSection("scripts", required: false)
            <hr />
            <footer>
                <p>&copy; 2017 - TFLDataExplorer</p>
            </footer>
        </div>
</body>
</html>